insert into NODE (id_node,name, parent_node_id) values (0,'racine',NULL);
insert into NODE (id_node,name, parent_node_id) values (2,"Réalisations",0);   
insert into NODE (id_node,name, parent_node_id) values (3,"Ressources pédagogiques",0);   
insert into NODE (id_node,name, parent_node_id) values (4,"Evaluation",0);   
insert into NODE (id_node,name, parent_node_id) values (5,"Comptes-rendus",0);   
insert into NODE (id_node,name, parent_node_id) values (6,"Actus - infos ASL",0);   
insert into NODE (id_node,name, parent_node_id) values (7,"Témoignages apprenants",2);   
insert into NODE (id_node,name, parent_node_id) values (8,"Sorties apprenants",2);   
insert into NODE (id_node,name, parent_node_id) values (9,"Recettes",2);   
insert into NODE (id_node,name, parent_node_id) values (10,"Photos",2);   
insert into NODE (id_node,name, parent_node_id) values (11,"Musiques du pays",2);   
insert into NODE (id_node,name, parent_node_id) values (12,"Ma ville natale",7);   
insert into NODE (id_node,name, parent_node_id) values (13,"Ma ville-photos utiles",12);   
insert into NODE (id_node,name, parent_node_id) values (14,"vie quotidienne",3);   
insert into NODE (id_node,name, parent_node_id) values (15,"Vie citoyenne",3);   
insert into NODE (id_node,name, parent_node_id) values (16,"Temps et Espace",3);   
insert into NODE (id_node,name, parent_node_id) values (17,"Ressources linguistiques",3);   
insert into NODE (id_node,name, parent_node_id) values (18,"Ressources Numériques",3);   
insert into NODE (id_node,name, parent_node_id) values (19,"La Santé",3);   
insert into NODE (id_node,name, parent_node_id) values (20,"Jeux",3);   
insert into NODE (id_node,name, parent_node_id) values (21,"Identité",3);   
insert into NODE (id_node,name, parent_node_id) values (22,"Emploi",3);   
insert into NODE (id_node,name, parent_node_id) values (23,"Culture française",3);   
insert into NODE (id_node,name, parent_node_id) values (24,"Administrations",3);   
insert into NODE (id_node,name, parent_node_id) values (25,"achats -alimentation-courses",14);   
insert into NODE (id_node,name, parent_node_id) values (26,"Logement",14);   
insert into NODE (id_node,name, parent_node_id) values (27,"La poste - le courrier",14);   
insert into NODE (id_node,name, parent_node_id) values (28,"La banque - l'argent",14);   
insert into NODE (id_node,name, parent_node_id) values (29,"Ecole",14);   
insert into NODE (id_node,name, parent_node_id) values (30,"Chiffres et nombres",14);   
insert into NODE (id_node,name, parent_node_id) values (31,"E",25);   
insert into NODE (id_node,name, parent_node_id) values (32,"D",25);   
insert into NODE (id_node,name, parent_node_id) values (33,"A",25);   
insert into NODE (id_node,name, parent_node_id) values (34,"E",26);   
insert into NODE (id_node,name, parent_node_id) values (35,"D",26);   
insert into NODE (id_node,name, parent_node_id) values (36,"A",26);   
insert into NODE (id_node,name, parent_node_id) values (37,"E",27);   
insert into NODE (id_node,name, parent_node_id) values (38,"D",27);   
insert into NODE (id_node,name, parent_node_id) values (39,"A",27);   
insert into NODE (id_node,name, parent_node_id) values (40,"E",28);   
insert into NODE (id_node,name, parent_node_id) values (41,"D",28);   
insert into NODE (id_node,name, parent_node_id) values (42,"A",28);   
insert into NODE (id_node,name, parent_node_id) values (43,"E",29);   
insert into NODE (id_node,name, parent_node_id) values (44,"D",29);   
insert into NODE (id_node,name, parent_node_id) values (45,"A",29);   
insert into NODE (id_node,name, parent_node_id) values (46,"E",30);   
insert into NODE (id_node,name, parent_node_id) values (47,"D",30);   
insert into NODE (id_node,name, parent_node_id) values (48,"A",30);   
insert into NODE (id_node,name, parent_node_id) values (49,"Naturalisation",15);   
insert into NODE (id_node,name, parent_node_id) values (50,"Institutions - Hist Géo",15);   
insert into NODE (id_node,name, parent_node_id) values (51,"Environnement",15);   
insert into NODE (id_node,name, parent_node_id) values (52,"Citoyenneté Laïcité",15);   
insert into NODE (id_node,name, parent_node_id) values (53,"Institutions vie politique",50);   
insert into NODE (id_node,name, parent_node_id) values (54,"Histoire géographie de France",50);   
insert into NODE (id_node,name, parent_node_id) values (55,"E",53);   
insert into NODE (id_node,name, parent_node_id) values (56,"D",53);   
insert into NODE (id_node,name, parent_node_id) values (57,"A",53);   
insert into NODE (id_node,name, parent_node_id) values (58,"E",54);   
insert into NODE (id_node,name, parent_node_id) values (59,"D",54);   
insert into NODE (id_node,name, parent_node_id) values (60,"A",54);   
insert into NODE (id_node,name, parent_node_id) values (61,"E",51);   
insert into NODE (id_node,name, parent_node_id) values (62,"D",51);   
insert into NODE (id_node,name, parent_node_id) values (63,"A",51);   
insert into NODE (id_node,name, parent_node_id) values (64,"E",52);   
insert into NODE (id_node,name, parent_node_id) values (65,"D",52);   
insert into NODE (id_node,name, parent_node_id) values (66,"A",52);   
insert into NODE (id_node,name, parent_node_id) values (67,"Temps",16);   
insert into NODE (id_node,name, parent_node_id) values (68,"Espace",16);   
insert into NODE (id_node,name, parent_node_id) values (69,"E",67);   
insert into NODE (id_node,name, parent_node_id) values (70,"D",67);   
insert into NODE (id_node,name, parent_node_id) values (71,"A",67);   
insert into NODE (id_node,name, parent_node_id) values (72,"E",68);   
insert into NODE (id_node,name, parent_node_id) values (73,"D",68);   
insert into NODE (id_node,name, parent_node_id) values (74,"A",68);   
insert into NODE (id_node,name, parent_node_id) values (75,"Vocabulaire - Orthographe",17);   
insert into NODE (id_node,name, parent_node_id) values (76,"Verbes - Conjugaison",17);   
insert into NODE (id_node,name, parent_node_id) values (77,"Oral - Phonétique",17);   
insert into NODE (id_node,name, parent_node_id) values (78,"Grammaire",17);   
insert into NODE (id_node,name, parent_node_id) values (79,"Alphabetisation",17);   
insert into NODE (id_node,name, parent_node_id) values (80,"E",75);   
insert into NODE (id_node,name, parent_node_id) values (81,"D",75);   
insert into NODE (id_node,name, parent_node_id) values (82,"A",75);   
insert into NODE (id_node,name, parent_node_id) values (83,"Présent",76);   
insert into NODE (id_node,name, parent_node_id) values (84,"Passé",76);   
insert into NODE (id_node,name, parent_node_id) values (85,"Futur",76);   
insert into NODE (id_node,name, parent_node_id) values (86,"Divers",76);   
insert into NODE (id_node,name, parent_node_id) values (87,"E",83);   
insert into NODE (id_node,name, parent_node_id) values (88,"D",83);   
insert into NODE (id_node,name, parent_node_id) values (89,"A",83);   
insert into NODE (id_node,name, parent_node_id) values (90,"E",84);   
insert into NODE (id_node,name, parent_node_id) values (91,"A",84);   
insert into NODE (id_node,name, parent_node_id) values (92,"E",85);   
insert into NODE (id_node,name, parent_node_id) values (93,"D",85);   
insert into NODE (id_node,name, parent_node_id) values (94,"A",85);   
insert into NODE (id_node,name, parent_node_id) values (95,"E",86);   
insert into NODE (id_node,name, parent_node_id) values (96,"D",86);   
insert into NODE (id_node,name, parent_node_id) values (97,"A",86);   
insert into NODE (id_node,name, parent_node_id) values (98,"Péda phonétique",77);   
insert into NODE (id_node,name, parent_node_id) values (99,"E",77);   
insert into NODE (id_node,name, parent_node_id) values (100,"D",77);   
insert into NODE (id_node,name, parent_node_id) values (101,"A",77);   
insert into NODE (id_node,name, parent_node_id) values (102,"Grammaire",78);   
insert into NODE (id_node,name, parent_node_id) values (103,"E",102);   
insert into NODE (id_node,name, parent_node_id) values (104,"D",102);   
insert into NODE (id_node,name, parent_node_id) values (105,"A",102);   
insert into NODE (id_node,name, parent_node_id) values (106,"Fiches péda",79);   
insert into NODE (id_node,name, parent_node_id) values (107,"Alphabet",79);   
insert into NODE (id_node,name, parent_node_id) values (108,"Fiches Denis ALPHA",106);   
insert into NODE (id_node,name, parent_node_id) values (109,"Ressources en ligne",18);   
insert into NODE (id_node,name, parent_node_id) values (110,"Formations  numériques  ASL",18);   
insert into NODE (id_node,name, parent_node_id) values (111,"Formation Informatique",18);   
insert into NODE (id_node,name, parent_node_id) values (112,"Banque d'images",18);   
insert into NODE (id_node,name, parent_node_id) values (113,"E",110);   
insert into NODE (id_node,name, parent_node_id) values (114,"D",110);   
insert into NODE (id_node,name, parent_node_id) values (115,"A",110);   
insert into NODE (id_node,name, parent_node_id) values (116,"docs authentiques",112);   
insert into NODE (id_node,name, parent_node_id) values (117,"Temps & Espace",112);   
insert into NODE (id_node,name, parent_node_id) values (118,"Sports & loisirs",112);   
insert into NODE (id_node,name, parent_node_id) values (119,"Images Culture française",112);   
insert into NODE (id_node,name, parent_node_id) values (120,"Identité Famille",112);   
insert into NODE (id_node,name, parent_node_id) values (121,"Divers",112);   
insert into NODE (id_node,name, parent_node_id) values (122,"Corps Santé",112);   
insert into NODE (id_node,name, parent_node_id) values (123,"Animaux",112);   
insert into NODE (id_node,name, parent_node_id) values (124,"Alimentation & courses",112);   
insert into NODE (id_node,name, parent_node_id) values (125,"le corps",19);   
insert into NODE (id_node,name, parent_node_id) values (126,"la maladie-les soins",19);   
insert into NODE (id_node,name, parent_node_id) values (127,"E",125);   
insert into NODE (id_node,name, parent_node_id) values (128,"D",125);   
insert into NODE (id_node,name, parent_node_id) values (129,"A",125);   
insert into NODE (id_node,name, parent_node_id) values (130,"E",126);   
insert into NODE (id_node,name, parent_node_id) values (131,"D",126);   
insert into NODE (id_node,name, parent_node_id) values (132,"A",126);   
insert into NODE (id_node,name, parent_node_id) values (133,"jeux de rôle",20);   
insert into NODE (id_node,name, parent_node_id) values (134,"jeux de pistes",20);   
insert into NODE (id_node,name, parent_node_id) values (135,"jeux de l'oie",20);   
insert into NODE (id_node,name, parent_node_id) values (136,"jeu de familles",20);   
insert into NODE (id_node,name, parent_node_id) values (137,"Jeux thèmes",20);   
insert into NODE (id_node,name, parent_node_id) values (138,"Fiches de jeux",20);   
insert into NODE (id_node,name, parent_node_id) values (139,"E",133);   
insert into NODE (id_node,name, parent_node_id) values (140,"D",133);   
insert into NODE (id_node,name, parent_node_id) values (141,"A",133);   
insert into NODE (id_node,name, parent_node_id) values (142,"E",134);   
insert into NODE (id_node,name, parent_node_id) values (143,"D",134);   
insert into NODE (id_node,name, parent_node_id) values (144,"A",134);   
insert into NODE (id_node,name, parent_node_id) values (145,"E",135);   
insert into NODE (id_node,name, parent_node_id) values (146,"D",135);   
insert into NODE (id_node,name, parent_node_id) values (147,"A",135);   
insert into NODE (id_node,name, parent_node_id) values (148,"E",136);   
insert into NODE (id_node,name, parent_node_id) values (149,"D",136);   
insert into NODE (id_node,name, parent_node_id) values (150,"A",136);   
insert into NODE (id_node,name, parent_node_id) values (151,"Jeu des femmes françaises célèbres - D E A -j",148);   
insert into NODE (id_node,name, parent_node_id) values (152,"Jeu des femmes françaises célèbres - D E A -j",149);   
insert into NODE (id_node,name, parent_node_id) values (153,"Jeu des femmes françaises célèbres - D E A -j",150);   
insert into NODE (id_node,name, parent_node_id) values (154,"E",137);   
insert into NODE (id_node,name, parent_node_id) values (155,"D",137);   
insert into NODE (id_node,name, parent_node_id) values (156,"A",137);   
insert into NODE (id_node,name, parent_node_id) values (157,"E",138);   
insert into NODE (id_node,name, parent_node_id) values (158,"D",138);   
insert into NODE (id_node,name, parent_node_id) values (159,"A",138);   
insert into NODE (id_node,name, parent_node_id) values (160,"Vêtements Apparence",21);   
insert into NODE (id_node,name, parent_node_id) values (161,"Sports et loisirs",21);   
insert into NODE (id_node,name, parent_node_id) values (162,"Se présenter Les goûts",21);   
insert into NODE (id_node,name, parent_node_id) values (163,"La famille",21);   
insert into NODE (id_node,name, parent_node_id) values (164,"Codes sociaux et culturels",21);   
insert into NODE (id_node,name, parent_node_id) values (165,"E",160);   
insert into NODE (id_node,name, parent_node_id) values (166,"D",160);   
insert into NODE (id_node,name, parent_node_id) values (167,"A",160);   
insert into NODE (id_node,name, parent_node_id) values (168,"E",161);   
insert into NODE (id_node,name, parent_node_id) values (169,"D",161);   
insert into NODE (id_node,name, parent_node_id) values (170,"A",161);   
insert into NODE (id_node,name, parent_node_id) values (171,"E",162);   
insert into NODE (id_node,name, parent_node_id) values (172,"D",162);   
insert into NODE (id_node,name, parent_node_id) values (173,"A",162);   
insert into NODE (id_node,name, parent_node_id) values (174,"E",163);   
insert into NODE (id_node,name, parent_node_id) values (175,"D",163);   
insert into NODE (id_node,name, parent_node_id) values (176,"A",163);   
insert into NODE (id_node,name, parent_node_id) values (177,"E",164);   
insert into NODE (id_node,name, parent_node_id) values (178,"D",164);   
insert into NODE (id_node,name, parent_node_id) values (179,"A",164);   
insert into NODE (id_node,name, parent_node_id) values (180,"Métiers",22);   
insert into NODE (id_node,name, parent_node_id) values (181,"Insertion pro",22);   
insert into NODE (id_node,name, parent_node_id) values (182,"Docs de travail - marché du travail",22);   
insert into NODE (id_node,name, parent_node_id) values (183,"Compétences pro",22);   
insert into NODE (id_node,name, parent_node_id) values (184,"E",180);   
insert into NODE (id_node,name, parent_node_id) values (185,"D",180);   
insert into NODE (id_node,name, parent_node_id) values (186,"A",180);   
insert into NODE (id_node,name, parent_node_id) values (187,"E",181);   
insert into NODE (id_node,name, parent_node_id) values (188,"D",181);   
insert into NODE (id_node,name, parent_node_id) values (189,"A",181);   
insert into NODE (id_node,name, parent_node_id) values (190,"E",182);   
insert into NODE (id_node,name, parent_node_id) values (191,"D",182);   
insert into NODE (id_node,name, parent_node_id) values (192,"A",182);   
insert into NODE (id_node,name, parent_node_id) values (193,"E",183);   
insert into NODE (id_node,name, parent_node_id) values (194,"A",183);   
insert into NODE (id_node,name, parent_node_id) values (195,"Lieux de culture",23);   
insert into NODE (id_node,name, parent_node_id) values (196,"Habitudes, fêtes",23);   
insert into NODE (id_node,name, parent_node_id) values (197,"Expressions-argot",23);   
insert into NODE (id_node,name, parent_node_id) values (198,"Arts - Chansons-littérature",23);   
insert into NODE (id_node,name, parent_node_id) values (199,"E",195);   
insert into NODE (id_node,name, parent_node_id) values (200,"D",195);   
insert into NODE (id_node,name, parent_node_id) values (201,"A",195);   
insert into NODE (id_node,name, parent_node_id) values (202,"E",196);   
insert into NODE (id_node,name, parent_node_id) values (203,"D",196);   
insert into NODE (id_node,name, parent_node_id) values (204,"A",196);   
insert into NODE (id_node,name, parent_node_id) values (205,"E",197);   
insert into NODE (id_node,name, parent_node_id) values (206,"D",197);   
insert into NODE (id_node,name, parent_node_id) values (207,"A",197);   
insert into NODE (id_node,name, parent_node_id) values (208,"E",198);   
insert into NODE (id_node,name, parent_node_id) values (209,"D",198);   
insert into NODE (id_node,name, parent_node_id) values (210,"A",198);   
insert into NODE (id_node,name, parent_node_id) values (211,"E",24);   
insert into NODE (id_node,name, parent_node_id) values (212,"D",24);   
insert into NODE (id_node,name, parent_node_id) values (213,"A",24);   
insert into NODE (id_node,name, parent_node_id) values (214,"Sociolinguistique",4);   
insert into NODE (id_node,name, parent_node_id) values (215,"Linguistique",4);   
insert into NODE (id_node,name, parent_node_id) values (216,"E",214);   
insert into NODE (id_node,name, parent_node_id) values (217,"D",214);   
insert into NODE (id_node,name, parent_node_id) values (218,"ALPHA",214);   
insert into NODE (id_node,name, parent_node_id) values (219,"A",214);   
insert into NODE (id_node,name, parent_node_id) values (220,"TCF ANF",215);   
insert into NODE (id_node,name, parent_node_id) values (221,"E",215);   
insert into NODE (id_node,name, parent_node_id) values (222,"ALPHA D",215);   
insert into NODE (id_node,name, parent_node_id) values (223,"A",215);   
insert into NODE (id_node,name, parent_node_id) values (224,"familier et autre",223);   
insert into NODE (id_node,name, parent_node_id) values (225,"A - expression écrite",223);   
insert into NODE (id_node,name, parent_node_id) values (226,"A - expression orale",223);   
insert into NODE (id_node,name, parent_node_id) values (227,"A - compréhension écrite",223);   
insert into NODE (id_node,name, parent_node_id) values (228,"A - compréhension orale",223);   
insert into NODE (id_node,name, parent_node_id) values (229,"les fumeurs",228);   
insert into NODE (id_node,name, parent_node_id) values (230,"ben laden",228);   
insert into NODE (id_node,name, parent_node_id) values (231,"Séances",5);   
insert into NODE (id_node,name, parent_node_id) values (232,"Réunions",5);   
insert into NODE (id_node,name, parent_node_id) values (233,"Formations",5);   
insert into NODE (id_node,name, parent_node_id) values (234,"TCF ANF",231);   
insert into NODE (id_node,name, parent_node_id) values (235,"SOIR",231);   
insert into NODE (id_node,name, parent_node_id) values (236,"EO",231);   
insert into NODE (id_node,name, parent_node_id) values (237,"EE",231);   
insert into NODE (id_node,name, parent_node_id) values (238,"D",231);   
insert into NODE (id_node,name, parent_node_id) values (239,"AO",231);   
insert into NODE (id_node,name, parent_node_id) values (240,"ALPHA D",231);   
insert into NODE (id_node,name, parent_node_id) values (241,"ALPHA",231);   
insert into NODE (id_node,name, parent_node_id) values (242,"AE",231);   
insert into NODE (id_node,name, parent_node_id) values (243,"CR séances FLP Leslie Molotoff",235);   
insert into NODE (id_node,name, parent_node_id) values (244,"Pédagogie des ASL",6);   
insert into NODE (id_node,name, parent_node_id) values (245,"Actus Abbaye",6);   
insert into NODE (id_node,name, parent_node_id) values (246,"methode borel maisonny",244);   
insert into NODE (id_node,name, parent_node_id) values (247,"démarche - infos ASL",244);   
insert into NODE (id_node,name, parent_node_id) values (248,"cours master FLE",244);   
insert into NODE (id_node,name, parent_node_id) values (249,"Ressources biblio",244);   
insert into NODE (id_node,name, parent_node_id) values (250,"Balise ALPHA",244);   
insert into NODE (id_node,name, parent_node_id) values (251,"référentiels",247);   
insert into NODE (id_node,name, parent_node_id) values (252,"Master2",248);   
insert into NODE (id_node,name, parent_node_id) values (253,"Master 1",248);   
insert into NODE (id_node,name, parent_node_id) values (254,"ingénierie de formation",252);   
insert into NODE (id_node,name, parent_node_id) values (255,"rouages PNG",250);   
