insert into NODE (id_node,name, parent_node_id) values (0,'Ressourcepeda',NULL);
insert into NODE (id_node,name, parent_node_id) values (2,'vie quotidienne',0);   
insert into NODE (id_node,name, parent_node_id) values (3,'Vie citoyenne',0);   
insert into NODE (id_node,name, parent_node_id) values (4,'Temps et Espace',0);   
insert into NODE (id_node,name, parent_node_id) values (5,'Ressources linguistiques',0);   
insert into NODE (id_node,name, parent_node_id) values (6,'Ressources Numériques',0);   
insert into NODE (id_node,name, parent_node_id) values (7,'Pédagogie des ASL',0);   
insert into NODE (id_node,name, parent_node_id) values (8,'La Santé',0);   
insert into NODE (id_node,name, parent_node_id) values (9,'Jeux',0);   
insert into NODE (id_node,name, parent_node_id) values (10,'Identité',0);   
insert into NODE (id_node,name, parent_node_id) values (11,'Emploi',0);   
insert into NODE (id_node,name, parent_node_id) values (12,'Culture française',0);   
insert into NODE (id_node,name, parent_node_id) values (13,'Administrations',0);   
insert into NODE (id_node,name, parent_node_id) values (14,'achats -alimentation-courses',2);   
insert into NODE (id_node,name, parent_node_id) values (15,'Logement',2);   
insert into NODE (id_node,name, parent_node_id) values (16,'La poste - le courrier',2);   
insert into NODE (id_node,name, parent_node_id) values (17,'La banque - l_argent',2);   
insert into NODE (id_node,name, parent_node_id) values (18,'Ecole',2);   
insert into NODE (id_node,name, parent_node_id) values (19,'Chiffres et nombres',2);   
insert into NODE (id_node,name, parent_node_id) values (20,'E',14);   
insert into NODE (id_node,name, parent_node_id) values (21,'D',14);   
insert into NODE (id_node,name, parent_node_id) values (22,'A',14);   
insert into NODE (id_node,name, parent_node_id) values (23,'E',15);   
insert into NODE (id_node,name, parent_node_id) values (24,'D',15);   
insert into NODE (id_node,name, parent_node_id) values (25,'A',15);   
insert into NODE (id_node,name, parent_node_id) values (26,'E',16);   
insert into NODE (id_node,name, parent_node_id) values (27,'D',16);   
insert into NODE (id_node,name, parent_node_id) values (28,'A',16);   
insert into NODE (id_node,name, parent_node_id) values (29,'E',17);   
insert into NODE (id_node,name, parent_node_id) values (30,'D',17);   
insert into NODE (id_node,name, parent_node_id) values (31,'A',17);   
insert into NODE (id_node,name, parent_node_id) values (32,'E',18);   
insert into NODE (id_node,name, parent_node_id) values (33,'D',18);   
insert into NODE (id_node,name, parent_node_id) values (34,'A',18);   
insert into NODE (id_node,name, parent_node_id) values (35,'E',19);   
insert into NODE (id_node,name, parent_node_id) values (36,'D',19);   
insert into NODE (id_node,name, parent_node_id) values (37,'A',19);   
insert into NODE (id_node,name, parent_node_id) values (38,'Naturalisation',3);   
insert into NODE (id_node,name, parent_node_id) values (39,'Institutions - Hist Géo',3);   
insert into NODE (id_node,name, parent_node_id) values (40,'Environnement',3);   
insert into NODE (id_node,name, parent_node_id) values (41,'Citoyenneté Laïcité',3);   
insert into NODE (id_node,name, parent_node_id) values (42,'Institutions vie politique',39);   
insert into NODE (id_node,name, parent_node_id) values (43,'Histoire géographie de France',39);   
insert into NODE (id_node,name, parent_node_id) values (44,'E',42);   
insert into NODE (id_node,name, parent_node_id) values (45,'D',42);   
insert into NODE (id_node,name, parent_node_id) values (46,'A',42);   
insert into NODE (id_node,name, parent_node_id) values (47,'E',40);   
insert into NODE (id_node,name, parent_node_id) values (48,'D',40);   
insert into NODE (id_node,name, parent_node_id) values (49,'A',40);   
insert into NODE (id_node,name, parent_node_id) values (50,'E',41);   
insert into NODE (id_node,name, parent_node_id) values (51,'A',41);   
insert into NODE (id_node,name, parent_node_id) values (52,'Transports plans directions',4);   
insert into NODE (id_node,name, parent_node_id) values (53,'Heures et calendrier',4);   
insert into NODE (id_node,name, parent_node_id) values (54,'E',52);   
insert into NODE (id_node,name, parent_node_id) values (55,'D',52);   
insert into NODE (id_node,name, parent_node_id) values (56,'A',52);   
insert into NODE (id_node,name, parent_node_id) values (57,'E',53);   
insert into NODE (id_node,name, parent_node_id) values (58,'D',53);   
insert into NODE (id_node,name, parent_node_id) values (59,'A',53);   
insert into NODE (id_node,name, parent_node_id) values (60,'grammaire et conjugaison',5);   
insert into NODE (id_node,name, parent_node_id) values (61,'Oral - Phonétique',5);   
insert into NODE (id_node,name, parent_node_id) values (62,'Alphabetisation',5);   
insert into NODE (id_node,name, parent_node_id) values (63,'Verbes et conjugaison',60);   
insert into NODE (id_node,name, parent_node_id) values (64,'Orthographe',60);   
insert into NODE (id_node,name, parent_node_id) values (65,'Grammaire',60);   
insert into NODE (id_node,name, parent_node_id) values (66,'Genre et nb',60);   
insert into NODE (id_node,name, parent_node_id) values (67,'Présent',63);   
insert into NODE (id_node,name, parent_node_id) values (68,'Passé',63);   
insert into NODE (id_node,name, parent_node_id) values (69,'Futur',63);   
insert into NODE (id_node,name, parent_node_id) values (70,'Divers',63);   
insert into NODE (id_node,name, parent_node_id) values (71,'E',70);   
insert into NODE (id_node,name, parent_node_id) values (72,'D',70);   
insert into NODE (id_node,name, parent_node_id) values (73,'A',70);   
insert into NODE (id_node,name, parent_node_id) values (74,'E',64);   
insert into NODE (id_node,name, parent_node_id) values (75,'D',64);   
insert into NODE (id_node,name, parent_node_id) values (76,'A',64);   
insert into NODE (id_node,name, parent_node_id) values (77,'E',65);   
insert into NODE (id_node,name, parent_node_id) values (78,'D',65);   
insert into NODE (id_node,name, parent_node_id) values (79,'A',65);   
insert into NODE (id_node,name, parent_node_id) values (80,'E',66);   
insert into NODE (id_node,name, parent_node_id) values (81,'D',66);   
insert into NODE (id_node,name, parent_node_id) values (82,'A',66);   
insert into NODE (id_node,name, parent_node_id) values (83,'Péda phonétique',61);   
insert into NODE (id_node,name, parent_node_id) values (84,'E',61);   
insert into NODE (id_node,name, parent_node_id) values (85,'D',61);   
insert into NODE (id_node,name, parent_node_id) values (86,'A',61);   
insert into NODE (id_node,name, parent_node_id) values (87,'Fiches péda',62);   
insert into NODE (id_node,name, parent_node_id) values (88,'Alphabet',62);   
insert into NODE (id_node,name, parent_node_id) values (89,'Fiches Denis ALPHA',87);   
insert into NODE (id_node,name, parent_node_id) values (90,'Ressources en ligne',6);   
insert into NODE (id_node,name, parent_node_id) values (91,'Formations  numériques  ASL',6);   
insert into NODE (id_node,name, parent_node_id) values (92,'Formation Informatique',6);   
insert into NODE (id_node,name, parent_node_id) values (93,'Banque d_images',6);   
insert into NODE (id_node,name, parent_node_id) values (94,'docs authentiques',93);   
insert into NODE (id_node,name, parent_node_id) values (95,'Temps _ Espace',93);   
insert into NODE (id_node,name, parent_node_id) values (96,'Sports _ loisirs',93);   
insert into NODE (id_node,name, parent_node_id) values (97,'Images Culture française',93);   
insert into NODE (id_node,name, parent_node_id) values (98,'Identité Famille',93);   
insert into NODE (id_node,name, parent_node_id) values (99,'Divers',93);   
insert into NODE (id_node,name, parent_node_id) values (100,'Corps Santé',93);   
insert into NODE (id_node,name, parent_node_id) values (101,'Animaux',93);   
insert into NODE (id_node,name, parent_node_id) values (102,'Alimentation _ courses',93);   
insert into NODE (id_node,name, parent_node_id) values (103,'methode borel maisonny',7);   
insert into NODE (id_node,name, parent_node_id) values (104,'démarche - infos ASL',7);   
insert into NODE (id_node,name, parent_node_id) values (105,'cours master FLE',7);   
insert into NODE (id_node,name, parent_node_id) values (106,'Ressources biblio',7);   
insert into NODE (id_node,name, parent_node_id) values (107,'Balise ALPHA',7);   
insert into NODE (id_node,name, parent_node_id) values (108,'référentiels',104);   
insert into NODE (id_node,name, parent_node_id) values (109,'Master2',105);   
insert into NODE (id_node,name, parent_node_id) values (110,'Master 1',105);   
insert into NODE (id_node,name, parent_node_id) values (111,'ingénierie de formation',109);   
insert into NODE (id_node,name, parent_node_id) values (112,'rouages PNG',107);   
insert into NODE (id_node,name, parent_node_id) values (113,'le corps',8);   
insert into NODE (id_node,name, parent_node_id) values (114,'la maladie-les soins',8);   
insert into NODE (id_node,name, parent_node_id) values (115,'E',113);   
insert into NODE (id_node,name, parent_node_id) values (116,'D',113);   
insert into NODE (id_node,name, parent_node_id) values (117,'E',114);   
insert into NODE (id_node,name, parent_node_id) values (118,'D',114);   
insert into NODE (id_node,name, parent_node_id) values (119,'A',114);   
insert into NODE (id_node,name, parent_node_id) values (120,'jeux de rôle',9);   
insert into NODE (id_node,name, parent_node_id) values (121,'jeux de pistes',9);   
insert into NODE (id_node,name, parent_node_id) values (122,'jeux de l_oie',9);   
insert into NODE (id_node,name, parent_node_id) values (123,'jeu de familles',9);   
insert into NODE (id_node,name, parent_node_id) values (124,'Jeux thèmes',9);   
insert into NODE (id_node,name, parent_node_id) values (125,'Fiches de jeux',9);   
insert into NODE (id_node,name, parent_node_id) values (126,'E',120);   
insert into NODE (id_node,name, parent_node_id) values (127,'D',120);   
insert into NODE (id_node,name, parent_node_id) values (128,'A',120);   
insert into NODE (id_node,name, parent_node_id) values (129,'E',121);   
insert into NODE (id_node,name, parent_node_id) values (130,'D',121);   
insert into NODE (id_node,name, parent_node_id) values (131,'A',121);   
insert into NODE (id_node,name, parent_node_id) values (132,'E',122);   
insert into NODE (id_node,name, parent_node_id) values (133,'D',122);   
insert into NODE (id_node,name, parent_node_id) values (134,'A',122);   
insert into NODE (id_node,name, parent_node_id) values (135,'Jeu des femmes françaises célèbres',123);   
insert into NODE (id_node,name, parent_node_id) values (136,'E',124);   
insert into NODE (id_node,name, parent_node_id) values (137,'D',124);   
insert into NODE (id_node,name, parent_node_id) values (138,'A',124);   
insert into NODE (id_node,name, parent_node_id) values (139,'E',125);   
insert into NODE (id_node,name, parent_node_id) values (140,'D',125);   
insert into NODE (id_node,name, parent_node_id) values (141,'A',125);   
insert into NODE (id_node,name, parent_node_id) values (142,'Vêtements Apparence',10);   
insert into NODE (id_node,name, parent_node_id) values (143,'Sports et loisirs',10);   
insert into NODE (id_node,name, parent_node_id) values (144,'Se présenter Les goûts',10);   
insert into NODE (id_node,name, parent_node_id) values (145,'La famille',10);   
insert into NODE (id_node,name, parent_node_id) values (146,'Codes sociaux et culturels',10);   
insert into NODE (id_node,name, parent_node_id) values (147,'E',142);   
insert into NODE (id_node,name, parent_node_id) values (148,'D',142);   
insert into NODE (id_node,name, parent_node_id) values (149,'A',142);   
insert into NODE (id_node,name, parent_node_id) values (150,'E',143);   
insert into NODE (id_node,name, parent_node_id) values (151,'D',143);   
insert into NODE (id_node,name, parent_node_id) values (152,'A',143);   
insert into NODE (id_node,name, parent_node_id) values (153,'E',144);   
insert into NODE (id_node,name, parent_node_id) values (154,'D',144);   
insert into NODE (id_node,name, parent_node_id) values (155,'A',144);   
insert into NODE (id_node,name, parent_node_id) values (156,'E',145);   
insert into NODE (id_node,name, parent_node_id) values (157,'D',145);   
insert into NODE (id_node,name, parent_node_id) values (158,'A',145);   
insert into NODE (id_node,name, parent_node_id) values (159,'E',146);   
insert into NODE (id_node,name, parent_node_id) values (160,'D',146);   
insert into NODE (id_node,name, parent_node_id) values (161,'A',146);   
insert into NODE (id_node,name, parent_node_id) values (162,'Métiers',11);   
insert into NODE (id_node,name, parent_node_id) values (163,'Insertion pro',11);   
insert into NODE (id_node,name, parent_node_id) values (164,'Docs de travail - marché du travail',11);   
insert into NODE (id_node,name, parent_node_id) values (165,'Compétences pro',11);   
insert into NODE (id_node,name, parent_node_id) values (166,'E',162);   
insert into NODE (id_node,name, parent_node_id) values (167,'D',162);   
insert into NODE (id_node,name, parent_node_id) values (168,'A',162);   
insert into NODE (id_node,name, parent_node_id) values (169,'E',163);   
insert into NODE (id_node,name, parent_node_id) values (170,'D',163);   
insert into NODE (id_node,name, parent_node_id) values (171,'A',163);   
insert into NODE (id_node,name, parent_node_id) values (172,'E',164);   
insert into NODE (id_node,name, parent_node_id) values (173,'D',164);   
insert into NODE (id_node,name, parent_node_id) values (174,'A',164);   
insert into NODE (id_node,name, parent_node_id) values (175,'E',165);   
insert into NODE (id_node,name, parent_node_id) values (176,'A',165);   
insert into NODE (id_node,name, parent_node_id) values (177,'Lieux de culture',12);   
insert into NODE (id_node,name, parent_node_id) values (178,'Habitudes, fêtes',12);   
insert into NODE (id_node,name, parent_node_id) values (179,'Expressions-argot',12);   
insert into NODE (id_node,name, parent_node_id) values (180,'Chansons-littérature',12);   
insert into NODE (id_node,name, parent_node_id) values (181,'E',177);   
insert into NODE (id_node,name, parent_node_id) values (182,'D',177);   
insert into NODE (id_node,name, parent_node_id) values (183,'A',177);   
insert into NODE (id_node,name, parent_node_id) values (184,'E',178);   
insert into NODE (id_node,name, parent_node_id) values (185,'D',178);   
insert into NODE (id_node,name, parent_node_id) values (186,'A',178);   
insert into NODE (id_node,name, parent_node_id) values (187,'E',179);   
insert into NODE (id_node,name, parent_node_id) values (188,'D',179);   
insert into NODE (id_node,name, parent_node_id) values (189,'A',179);   
insert into NODE (id_node,name, parent_node_id) values (190,'E',180);   
insert into NODE (id_node,name, parent_node_id) values (191,'D',180);   
insert into NODE (id_node,name, parent_node_id) values (192,'A',180);   
insert into NODE (id_node,name, parent_node_id) values (193,'E',13);   
insert into NODE (id_node,name, parent_node_id) values (194,'D',13);   
insert into NODE (id_node,name, parent_node_id) values (195,'A',13);   
