<?php session_start(); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Proposer un document</title>
	<link rel="stylesheet" type="text/css" href="view.css" media="all">
	<script type="text/javascript" src="view.js"></script>

</head>

<body id="main_body">

	<img id="top" src="top.png" alt="">
	<div id="form_container">

		<h1><a>Proposer un document</a></h1>
		<form id="form_116196" class="appnitro" enctype="multipart/form-data" method="post" action="traitement-proposer.php">
			<div class="form_description">
				<h2>Proposer un document</h2>
				<p>Ce formulaire nous aidera a traiter au mieux le document que vous nous proposez</p>
			</div>
			<ul>

				<li id="li_2">
					<label class="description" for="element_2">Titre </label>
					<div>
						<input required id="element_2" name="titre" class="element text medium" type="text" maxlength="255" value="" />
					</div>
					<p class="guidelines" id="guide_2"><small>Titre de votre document</small></p>
				</li>
				<li id="li_3">
					<label class="description" for="element_3">Description </label>
					<div>
						<textarea required id="element_3" name="description" class="element textarea medium"></textarea>
					</div>
					<p class="guidelines" id="guide_3"><small>Description rapide de votre document
							En quoi est-il une bonne ressource pédagogique ? </small></p>
				</li>
				<li id="li_1">
					<label class="description" for="element_1">Upload a File </label>
					<div>
						<input type="hidden" name="MAX_FILE_SIZE" value="5000000" />

						<input required id="element_1" name="fileToUpload" class="element file" type="file" />
					</div>
					<p class="guidelines" id="guide_1"><small>Format possible : image/audio/.doc/.docx/.pdf/.odt/.odp/.ppt/.pptx

							Taille maximal par fichier : 5Mo </small></p>
				</li>
				<li id="li_4">
					<label class="description" for="element_4">Etiquettes </label>
					<div>
						<input required id="element_4" name="tags" class="element text medium" type="text" maxlength="255" value="" />
					</div>
					<p class="guidelines" id="guide_4"><small>Séparer les étiquettes par des caracteres "+"
							Ces etiquettes nous aiderons a mieux rechercher votre document dans le cas ou nous ajoutons celui-ci à notre base </small></p>
				</li>
				<!--
				<li id="li_5">
					<label class="description" for="element_5">Email </label>
					<div>
						<input id="element_5" name="mail" class="element text medium" type="text" maxlength="255" value="" />
					</div>
				</li>
				-->
				<li class="buttons">
					<input type="hidden" name="form_id" value="116196" />
					<input type="reset" value="Reinitialiser">
					<input id="saveForm" class="button_text" type="submit" name="submit" value="Proposer" />
				</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
</body>

</html>