<?php session_start() ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">

<head>
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
	<title>Deplacer un fichier</title>
	<link rel="stylesheet" type="text/css" href="view.css" media="all">
	<script type="text/javascript" src="view.js"></script>
	<script type="text/javascript" src="deplacer.js"></script>


</head>

<body id="main_body" onload="init()">

	<img id="top" src="top.png" alt="">
	<div id="form_container">

		<h1><a>Deplacer un fichier</a></h1>
		<form id="form_116357" class="appnitro" method="post" action="">
			<div class="form_description">
				<h2>Deplacer un fichier</h2>
				<p>Vous pourrez choisir successivement selon l'arborescence de la base de données</p>
			</div>
			<ul>
				<li id="li_1">
					<label class="description" for="element_1"> </label>
					<div>
						<input type="text" id="nom" name="nom" readonly value="">
						<input type="text" id="id_doc" name="id_doc"readonly value="">
					</div>
					<p class="guidelines" id="guide_1"><small>Nom et numero du document a déplacer</small></p>
				</li>

				<li id="li_2">
					<label class="description" for="element_1"> </label>
					<div>
						<ul id="parcours">
						</ul>
						<div id="listdoss">
							<H3>Listes des thématiques </H3>
							<ul id="dossbar">
							</ul>
						</div>
					</div>
					<p class="guidelines" id="guide_1"><small>Selectionnez parmis les thématiques
							D'autre sous thématique se presenterons selon votre choix au fur et à mesure</small></p>
							<input type="text" id="destination" name="destination" readonly value="">

						</li>
				



				<li class="buttons">
					<input type="hidden" name="form_id" value="116357" />

					<input id="saveForm" class="button_text" type="submit" name="submit" value="Submit" />
				</li>
			</ul>
		</form>
		<div id="footer">
			Generated by <a href="http://www.phpform.org">pForm</a>
		</div>
	</div>
	<img id="bottom" src="bottom.png" alt="">
</body>

</html>