SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_b23274_pour-faire-connaissance-themes.docx';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (451,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_586592_exo-vote.pdf';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (628,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_65cf72_galite-des-chances-1p.pdf';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (704,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_66bf53_galite-des-chances.pdf';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (704,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_0dbee5_agent-d-entretien.docx';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (713,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_0faeaf_verbes-d-action.pdf';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (723,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_acc2b2_le-pronom-y.pdf';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (744,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_d5ad9b_a-la-bibliotheque-abbaye.pdf';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (810,@iddoc);
SELECT (id_doc) INTO @iddoc FROM DOCUMENT WHERE nom ='ob_58cdc1_citations-paix.pdf';
insert into COMPTERENDU_DOCUMENT (COMPTERENDU_id_cr, DOCUMENT_id_doc) values (820,@iddoc);
